/**
 * @kehto/services — Shared types for reference service implementations.
 *
 * These types describe the internal state that services manage and expose
 * to the shell host via callbacks. They are NOT NIP-01 wire types.
 */

/**
 * A notification created by a napplet.
 *
 * @example
 * ```ts
 * const notification: Notification = {
 *   id: 'notif-1',
 *   windowId: 'win-1',
 *   title: 'New Message',
 *   body: 'You have a new message from Alice',
 *   read: false,
 *   createdAt: 1711800000,
 * };
 * ```
 */
export interface Notification {
  /** Unique notification identifier (generated by the service). */
  id: string;
  /** The napplet window that created this notification. */
  windowId: string;
  /** Short notification title. */
  title: string;
  /** Notification body/description. */
  body: string;
  /** Whether the notification has been read/acknowledged. */
  read: boolean;
  /** Unix timestamp (seconds) when the notification was created. */
  createdAt: number;
}

/**
 * Options for creating a notification service via createNotificationService().
 *
 * @example
 * ```ts
 * const notifService = createNotificationService({
 *   onChange: (notifications) => console.log('Notifications:', notifications.length),
 *   maxPerWindow: 50,
 * });
 * ```
 */
export interface NotificationServiceOptions {
  /**
   * Called when the notification list changes (create, dismiss, read).
   * The shell host uses this to update UI (toast, badge, etc.).
   */
  onChange?: (notifications: readonly Notification[]) => void;
  /**
   * Maximum notifications to retain per window. Oldest are evicted
   * when the limit is exceeded. Default: 100.
   */
  maxPerWindow?: number;
}
